version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.15.0
    steps:
      - checkout
      - run: yarn 
  test:
    docker:
      - image: circleci/node:11.15.0
    steps:
      - checkout
      - run: yarn 
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test